# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ccfdcc0085877ea7897fe47ef057f174c96293cee9ac3c44e9f76b31224159704be4c7e36c508544e417d8fb7b7ed7a36c98e3afff2fa395cb8491fa6f045e7d

test:
  secret_key_base: d5ccad7476efc27d7d5e60eb61be245d85666bac54f25db9dc93b1aa4eb1ae9294ff370adfaf63939a9b7d2ed71e497149c593dfc4d1cd2d2d0acadc6f41ab87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
